import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  route("login", "routes/login.tsx"),
  layout("routes/_layout.tsx", [
    index("routes/dashboard.tsx"),
    route("users", "routes/users.tsx"),
    route("admins", "routes/admins.tsx"),
    route("user-categories", "routes/user-categories.tsx"),
    route("home-features", "routes/home-features.tsx"),
    route("home-faqs", "routes/home-faqs.tsx"),
    route("home-about", "routes/home-about.tsx"),
    route("home-categories", "routes/home-categories.tsx"),
    route("site-texts", "routes/site-texts.tsx"),
    route("contact-messages", "routes/contact-messages.tsx"),
    route("site-contact", "routes/site-contact.tsx"),
    route("social-links", "routes/social-links.tsx"),
    route("legal-pages", "routes/legal-pages.tsx"),
    route("miq-subjects", "routes/miq-subjects.tsx"),
    route("miq-exampages", "routes/miq-exampages.tsx"),
    route("miq-exampages/:id/question-types", "routes/miq-question-types.tsx"),
    route("miq-exampages/:id/question-types/:qtId/subjects", "routes/miq-exampage-subjects.tsx"),
    route("miq-exampages/:id/question-types/:qtId/questions", "routes/miq-questions.tsx"),
    route("miq-exampages/:id/question-types/:qtId/subjects/:subjectId/questions", "routes/miq-questions-subject.tsx"),
    route("miq-exampages/:id/question-types/:qtId/questions/:questionId/options", "routes/miq-question-options.tsx"),
    route("miq-exampages/:id/question-types/:qtId/subjects/:subjectId/questions/:questionId/options", "routes/miq-question-options-subject.tsx"),
    route("exams", "routes/exams.tsx"),
    route("questions", "routes/questions.tsx"),
    route("applicant-subjects", "routes/applicant-subjects.tsx"),
    route("applicant-groups", "routes/applicant-groups.tsx"),
    route("applicant-exampages", "routes/applicant-exampages.tsx"),
    route("applicant-exampages/:id/groups", "routes/applicant-exampage-groups.tsx"),
    route("applicant-exampages/:id/groups/:groupId/subjects", "routes/applicant-group-subjects.tsx"),
    route("applicant-exampages/:id/groups/:groupId/subjects/:subjectId/questions", "routes/applicant-questions.tsx"),
  route("api/upload-applicant-image", "routes/api.upload-applicant-image.ts"),
  route("api/upload-applicant-audio", "routes/api.upload-applicant-audio.ts"),
    route("api/users-search", "routes/api.users-search.ts"),
    route("exam-registrations", "routes/exam-registrations.tsx"),
    route("results", "routes/results.tsx"),
    route("results/:id/grade", "routes/grade-applicant.tsx"),
    route("settings", "routes/settings.tsx"),
  ]),
] satisfies RouteConfig;
